// <auto-generated />
using System;
using Klicko_be.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klicko_be.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415155649_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("OrderNumber_seq")
                .StartsAt(100000000L);

            modelBuilder.Entity("Klicko_be.Models.Auth.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8d64359a-fda6-4096-b40d-f1375775244d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1f00a1d7-cbb6-44bf-bdc8-a3608b1284b9",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        },
                        new
                        {
                            Id = "849b8726-44b3-434b-9b18-48a4e8d4e9dd",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 593, DateTimeKind.Utc).AddTicks(6990));

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            AccessFailedCount = 0,
                            CartId = new Guid("ad0b8ebb-3e25-4c9f-a7dd-7e07c3e7ab3f"),
                            ConcurrencyStamp = "b36df503-0bc4-4197-9205-0a222bea4be8",
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ924mp2s2BX/BpdalZ6f2s1qlMl3fxdcEPcaKFV6BxA5frV73oVpuC1V9F4PHCJ2g==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "1e374ad4-bc4b-4abf-ba84-878d6d0f5e6c",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "d9ee1702-09f8-4ec2-ac09-7f41c05fcd4c",
                            AccessFailedCount = 0,
                            CartId = new Guid("59a9d57e-c339-4a73-8d02-69cc186a5385"),
                            ConcurrencyStamp = "f137d749-f909-4f96-8229-698bbab5023c",
                            Email = "seller@example.com",
                            EmailConfirmed = false,
                            FirstName = "Seller",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "SELLER@EXAMPLE.COM",
                            NormalizedUserName = "SELLER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJP1xbBcaikPe32EBy3MLTcexMUhKB7jQsEGuRiIlRJOWuiJwUGI/v0s83m7H70okg==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "1536c6ab-470a-44c0-a960-e19ad96affc2",
                            TwoFactorEnabled = false,
                            UserName = "seller@example.com"
                        },
                        new
                        {
                            Id = "21f6b4b5-9616-4380-a9d3-3ddb2f4b72c2",
                            AccessFailedCount = 0,
                            CartId = new Guid("b64a049a-6d76-4c1c-866c-e0169c92f1d6"),
                            ConcurrencyStamp = "81d84916-e48e-4772-ad20-9f0ceec51c6d",
                            Email = "user@example.com",
                            EmailConfirmed = false,
                            FirstName = "User",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL6u4Tox47kxNqt9nm4+vRn+SzahthaQ55UejBFFdJvvUNNCfqIWRI246s9wJiZ43A==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c1da45ea-16db-4d85-804e-3cb1cf34f689",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.Auth.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            RoleId = "8d64359a-fda6-4096-b40d-f1375775244d",
                            UserRoleId = new Guid("6f44a915-b24b-4034-9e18-0a1775210ef3")
                        },
                        new
                        {
                            UserId = "d9ee1702-09f8-4ec2-ac09-7f41c05fcd4c",
                            RoleId = "1f00a1d7-cbb6-44bf-bdc8-a3608b1284b9",
                            UserRoleId = new Guid("5224a9f4-547b-4300-8788-26d085155b48")
                        },
                        new
                        {
                            UserId = "21f6b4b5-9616-4380-a9d3-3ddb2f4b72c2",
                            RoleId = "849b8726-44b3-434b-9b18-48a4e8d4e9dd",
                            UserRoleId = new Guid("16cbe3b5-128b-4e00-9fbb-4e691b00280a")
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.CarryWith", b =>
                {
                    b.Property<Guid>("CarryWithId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarryWithId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("CarryWiths");

                    b.HasData(
                        new
                        {
                            CarryWithId = new Guid("37f66586-377d-48b0-8775-0f3ab4743fad"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("5440ef3c-3a70-441f-a437-8d83c846ab50"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("ed314f33-6a11-4c0e-b570-c7dd3b43017d"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("ddadd752-df1c-43f7-9466-dcb72fbcf262"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("25860663-e017-4e55-91f0-52e45470f4d3"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("40070abb-16f7-426e-8768-2f77bc7bc753"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("eba64c18-8396-4bcd-b169-e262b1dfa061"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("b6457b26-bef6-47b4-9637-aa49d76c43fd"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("3339d17f-4fd0-4942-b1de-fc2ba54c15fe"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("7f618cc7-2a38-4219-8ca8-84ac0541576e"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("44245cfb-c6b8-46d3-a4da-374a4595cbda"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("5ce0813b-3969-48cd-ba31-f649881c2f85"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("b7125708-7e08-4c1b-8bc7-4cb68bf36a1c"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("f7b8e6a9-267a-4cb1-8823-3d691d15a3e4"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("d4ad2834-0a9e-4a25-ab65-67fc7e9a2856"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("cebce589-6d9e-4c93-9ffb-769879360a58"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("2d6da007-4afa-4830-86d4-cdf5d7244de6"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("e6c86760-cf4c-41a5-8450-e085d3c407ec"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("5687e531-773b-4855-b3c0-d8124c3f325c"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("4dc78b29-e9b1-4fd0-8965-a59dae5ac784"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("3a73b99c-bc56-426d-aa3b-2668d270a81c"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("36ff9655-7ad0-4002-8e18-33a9b95f1dc5"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("cf9ffc4f-0db2-4957-a51d-2b919d755705"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("e2669eb7-0538-4ce0-9098-6916b04e7c1e"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("82b97673-c6cd-4dd2-8e10-27e93e19fec1"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("4607945b-e5c3-41d5-9984-0e6e9ebbb740"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("243df698-9bf6-4ec9-bc7f-9cbe3e02398d"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("f4d999e5-74db-44c3-9f55-8296cfd4f6a4"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("f7b79ffb-a746-4794-9dc7-c6981f23b76d"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("4ef3c543-9181-4fb9-8bb2-7433965af376"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("9f16a4a2-1fbf-4fad-b5a5-2d3318ebb5dc"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("f4237517-e5cf-4b3a-97c5-9fc40b26351a"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("1db350e1-5cb8-4d9f-ac82-1ba56f938047"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("44ca62ed-9961-4d8e-b236-73b3a775227d"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("a7e1b81a-d252-435a-9e50-48b5549e2aff"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("090db950-0043-4e93-98ed-6f65927b08d6"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("457ccc48-cca1-4c79-825b-6e6accdef6ba"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("a39149a6-00f8-44ec-a9a6-133560e8e73e"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("fa3469c9-f1a1-4ce0-be74-58aea3289418"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("b47847bd-c782-49fb-a7f8-b9449a2680b0"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("f82cbfbf-d01a-40ca-b175-20366f94fb4a"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("dd784099-5b3e-4231-bc9d-4c45cdc1e354"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("7ba9453c-a316-4fcc-a45b-99b8d4afab90"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("bcd5eacd-61b5-4bb7-986a-ec7ab5a13f69"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("7b4712ec-b86b-42b4-bde9-24b089ac4b77"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Name = "Acqua"
                        },
                        new
                        {
                            CarryWithId = new Guid("aaaa9a81-b420-45a9-9164-4640382cca71"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Name = "Abbigliamento comodo"
                        },
                        new
                        {
                            CarryWithId = new Guid("7b1a1b63-3584-4849-ba0d-1ccb54fd0fe3"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Name = "Scarpe adatte all'attività"
                        },
                        new
                        {
                            CarryWithId = new Guid("a85cef09-4f5f-4787-af53-977737955c1f"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Name = "Documento d'identità"
                        },
                        new
                        {
                            CarryWithId = new Guid("f5673096-288f-4a8d-a706-800cb9739930"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Name = "Macchina fotografica (opzionale)"
                        },
                        new
                        {
                            CarryWithId = new Guid("e90eb389-a733-4917-8c57-24bfbd072dc4"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Name = "Acqua"
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 594, DateTimeKind.Utc).AddTicks(5891));

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 594, DateTimeKind.Utc).AddTicks(6552));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartId = new Guid("ad0b8ebb-3e25-4c9f-a7dd-7e07c3e7ab3f"),
                            CreatedAt = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            UserId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051"
                        },
                        new
                        {
                            CartId = new Guid("59a9d57e-c339-4a73-8d02-69cc186a5385"),
                            CreatedAt = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            UserId = "d9ee1702-09f8-4ec2-ac09-7f41c05fcd4c"
                        },
                        new
                        {
                            CartId = new Guid("b64a049a-6d76-4c1c-866c-e0169c92f1d6"),
                            CreatedAt = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            UserId = "21f6b4b5-9616-4380-a9d3-3ddb2f4b72c2"
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.CartExperience", b =>
                {
                    b.Property<Guid>("CartExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 594, DateTimeKind.Utc).AddTicks(7256));

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CartExperienceId");

                    b.HasIndex("CartId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("CartExperiences");
                });

            modelBuilder.Entity("Klicko_be.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("da780fcf-074e-4e0c-b0b8-1bd8e0c0fa6f"),
                            Description = "Aria",
                            Icon = "aria.png",
                            Image = "aria.jpg",
                            Name = "Aria"
                        },
                        new
                        {
                            CategoryId = new Guid("6accf29d-8d1c-4edd-b48a-c70251516b99"),
                            Description = "Acqua",
                            Icon = "acqua.png",
                            Image = "acqua.jpg",
                            Name = "Acqua"
                        },
                        new
                        {
                            CategoryId = new Guid("6f3a957c-df09-437c-bc37-f069173eabe2"),
                            Description = "Motori",
                            Icon = "motori.png",
                            Image = "motori.jpg",
                            Name = "Motori"
                        },
                        new
                        {
                            CategoryId = new Guid("bda4ee71-af9c-46c6-b1bf-95f178773a2f"),
                            Description = "Trekking",
                            Icon = "trekking.png",
                            Image = "trekking.jpg",
                            Name = "Trekking"
                        },
                        new
                        {
                            CategoryId = new Guid("5fdffa0f-a615-43f2-aa15-88bc8dcec27f"),
                            Description = "Gastronomia",
                            Icon = "Gastronomia.png",
                            Image = "Gastronomia.jpg",
                            Name = "Gastronomia"
                        },
                        new
                        {
                            CategoryId = new Guid("48733fb8-deae-41b2-b0c6-4fab3c45cf93"),
                            Description = "Arte e Cultura",
                            Icon = "arteCultura.png",
                            Image = "arteCultura.jpg",
                            Name = "Arte e Cultura"
                        },
                        new
                        {
                            CategoryId = new Guid("1652310e-b8f3-43e7-bd9d-287f73f939b5"),
                            Description = "Avventura",
                            Icon = "avventura.png",
                            Image = "avventura.jpg",
                            Name = "Avventura"
                        },
                        new
                        {
                            CategoryId = new Guid("b70671a5-3989-4e7c-9cd5-c6343e09fcde"),
                            Description = "Relax",
                            Icon = "relax.png",
                            Image = "relax.jpg",
                            Name = "Relax"
                        },
                        new
                        {
                            CategoryId = new Guid("a4049ef8-1e86-48bf-b514-3930469ddcbd"),
                            Description = "Sport",
                            Icon = "sport.png",
                            Image = "sport.jpg",
                            Name = "Sport"
                        },
                        new
                        {
                            CategoryId = new Guid("7f13b386-b8af-4ed1-b42b-845e17f657c3"),
                            Description = "Città",
                            Icon = "citta.png",
                            Image = "citta.jpg",
                            Name = "Città"
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFreeCancellable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInEvidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastEditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 593, DateTimeKind.Utc).AddTicks(8805));

                    b.Property<DateTime>("LoadingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 593, DateTimeKind.Utc).AddTicks(7916));

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Organiser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserLastModifyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ValidityInMonths")
                        .HasColumnType("int");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserCreatorId");

                    b.HasIndex("UserLastModifyId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            CategoryId = new Guid("6f3a957c-df09-437c-bc37-f069173eabe2"),
                            CoverImage = "372a18e3-7932-4ef5-8471-99ce5f3e098a.jpg",
                            Description = "Vivi l'emozione di guidare una Ferrari F488 GTB sul mitico circuito di Formula 1 di Monza. Dopo un briefing teorico con un pilota professionista, avrai l'opportunità di metterti al volante di questa supercar italiana e percorrere diversi giri sul circuito. Sentirai l'adrenalina scorrere mentre acceleri sui rettilinei e affronti le curve leggendarie come la Parabolica. Un'esperienza che combina lusso, velocità e il fascino intramontabile del marchio Ferrari. Il pacchetto include anche un video ricordo della tua esperienza in pista.",
                            DescriptionShort = "Guida una Ferrari sul leggendario circuito di Monza",
                            Duration = "2 ore",
                            IncludedDescription = "Tutto il necessario per la guida: casco, tuta e assicurazione. Video ricordo dell'esperienza.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = true,
                            IsPopular = false,
                            LastEditDate = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2025, 4, 9, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 1,
                            Organiser = "Motor Experience",
                            Place = "Monza, Lombardia",
                            Price = 399m,
                            Sale = 0,
                            Title = "Ferrari Driving Experience a Monza",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 24
                        },
                        new
                        {
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            CategoryId = new Guid("5fdffa0f-a615-43f2-aa15-88bc8dcec27f"),
                            CoverImage = "350540d5-80b9-49fa-8fb2-8a58c80d149c.jpg",
                            Description = "Questa esperienza culinaria si svolge in un autentico castello toscano circondato da vigneti e uliveti. Sotto la guida di uno chef locale, imparerai a preparare un menu completo di piatti tradizionali toscani utilizzando ingredienti freschi provenienti direttamente dall'orto del castello e da produttori locali. Il corso inizia con una passeggiata nei giardini per raccogliere erbe aromatiche, seguita dalla preparazione di pasta fatta in casa, un secondo a base di carne e un dolce tipico. Al termine della lezione, gusterai i piatti preparati accompagnati dai vini prodotti nella tenuta. Un'esperienza che coinvolge tutti i sensi e ti permette di portare a casa ricette e tecniche autentiche.",
                            DescriptionShort = "Impara a cucinare i piatti tradizionali toscani con la guida di uno chef locale",
                            Duration = "5 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = true,
                            IsPopular = false,
                            LastEditDate = new DateTime(2023, 3, 15, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 3, 15, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 2,
                            Organiser = "Sapori d'Italia",
                            Place = "Chianti, Toscana",
                            Price = 150m,
                            Sale = 0,
                            Title = "Cucina toscana nella tenuta di un castello",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 12
                        },
                        new
                        {
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            CategoryId = new Guid("bda4ee71-af9c-46c6-b1bf-95f178773a2f"),
                            CoverImage = "f34f2a25-8e55-4826-8ce4-aca2a2a76c3a.jpg",
                            Description = "Il Sentiero degli Dei è uno dei percorsi di trekking più affascinanti d'Italia, che collega Agerola a Positano offrendo viste mozzafiato sulla Costiera Amalfitana. Questa escursione guidata ti porterà lungo antiche mulattiere e sentieri di montagna, attraverso terrazzamenti coltivati a limoni e ulivi, macchia mediterranea e boschi. Durante il cammino, potrai ammirare il blu intenso del mar Tirreno, le isole Li Galli e Capri, e i caratteristici villaggi aggrappati alle scogliere. La guida ti racconterà la storia e le leggende locali, e ti indicherà i luoghi migliori per scattare fotografie indimenticabili.",
                            DescriptionShort = "Esplora il famoso sentiero con viste panoramiche sulla Costiera Amalfitana",
                            Duration = "6 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = true,
                            IsPopular = false,
                            LastEditDate = new DateTime(2023, 4, 5, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 4, 5, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 2,
                            Organiser = "Italia Escursioni",
                            Place = "Costiera Amalfitana, Campania",
                            Price = 65m,
                            Sale = 0,
                            Title = "Trekking sul sentiero degli Dei",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 6
                        },
                        new
                        {
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            CategoryId = new Guid("da780fcf-074e-4e0c-b0b8-1bd8e0c0fa6f"),
                            CoverImage = "b33390f8-430a-456c-b821-83a8b9406043.jpg",
                            Description = "Un'esperienza indimenticabile che ti permetterà di ammirare il magnifico paesaggio toscano da una prospettiva unica. Il volo in mongolfiera al tramonto inizia con un brindisi di benvenuto mentre l'equipaggio prepara il pallone. Durante l'ascesa potrai godere della vista spettacolare delle colline dorate dal sole al tramonto, dei vigneti e degli uliveti che caratterizzano questa splendida regione. Il volo dura circa un'ora e si conclude con un brindisi con prosecco locale e uno spuntino con prodotti tipici.",
                            DescriptionShort = "Goditi un tramonto mozzafiato sorvolando le colline toscane",
                            Duration = "3 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = true,
                            LastEditDate = new DateTime(2023, 6, 15, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 6, 15, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 2,
                            Organiser = "Avventure Italiane",
                            Place = "Siena, Toscana",
                            Price = 249.99m,
                            Sale = 5,
                            Title = "Volo in mongolfiera al tramonto",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 8
                        },
                        new
                        {
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            CategoryId = new Guid("48733fb8-deae-41b2-b0c6-4fab3c45cf93"),
                            CoverImage = "280b9c0f-257e-4f05-b2db-84e704fda33d.jpg",
                            Description = "Vivi l'esperienza di fotografare Venezia in un momento magico, quando la città è avvolta nella luce dorata dell'alba e le strade sono ancora tranquille, senza turisti. Questo tour fotografico guidato da un fotografo professionista ti porterà nei luoghi più iconici e nei angoli nascosti della Serenissima, offrendoti l'opportunità di catturare immagini uniche. Il tour inizia in Piazza San Marco, quando è ancora deserta, per poi esplorare i canali minori, i ponti caratteristici e i campielli pittoreschi. Durante il percorso, riceverai consigli tecnici personalizzati e suggerimenti creativi per migliorare le tue fotografie. Il tour è adatto sia ai principianti che ai fotografi esperti, con qualsiasi tipo di macchina fotografica, anche smartphone.",
                            DescriptionShort = "Cattura l amagia di Venezia nelle prime luci del giorno",
                            Duration = "3 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = true,
                            LastEditDate = new DateTime(2023, 5, 12, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 5, 12, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 2,
                            Organiser = "Venezia Autentica",
                            Place = "Venezia, Veneto",
                            Price = 95m,
                            Sale = 0,
                            Title = "Tour fotografico di Venezia all'alba",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 8
                        },
                        new
                        {
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            CategoryId = new Guid("5fdffa0f-a615-43f2-aa15-88bc8dcec27f"),
                            CoverImage = "4949849a-cc7a-4481-9c77-929fdbb71310.jpg",
                            Description = "Un'esperienza sensoriale completa nel cuore della campagna toscana, in una cantina storica scavata nel tufo. Questa degustazione guidata ti permetterà di conoscere i segreti della vinificazione, dalla coltivazione dell'uva all'invecchiamento in botte. Accompagnato da un sommelier esperto, percorrerai le gallerie sotterranee dove riposano le botti centenarie, mantenute alla temperatura perfetta dal microclima naturale. La degustazione include sei vini pregiati della tenuta, tra cui Chianti Classico, Super Tuscan e Vin Santo, accompagnati da pane toscano, olio extravergine d'oliva di produzione propria, formaggi locali e salumi artigianali. Durante l'esperienza, imparerai le tecniche di degustazione professionale e come abbinare correttamente il vino al cibo.",
                            DescriptionShort = "Scopri i segreti del vino in una cantina medievale",
                            Duration = "2 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = true,
                            LastEditDate = new DateTime(2023, 7, 20, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 7, 20, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 2,
                            Organiser = "Cantine Toscane",
                            Place = "Montepulciano, Toscana",
                            Price = 75m,
                            Sale = 0,
                            Title = "Degustazione di vini in cantina sotterranea",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 12
                        },
                        new
                        {
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            CategoryId = new Guid("6accf29d-8d1c-4edd-b48a-c70251516b99"),
                            CoverImage = "a8b9cf9c-4f8e-4e18-8413-bf5de4cb4b3c.jpg",
                            Description = "Preparati a vivere un'avventura emozionante nelle acque cristalline del fiume Nera, situato nel cuore dell'Umbria. Questa esperienza di rafting ti permetterà di affrontare rapide di diversa difficoltà sotto la guida di istruttori professionisti. Prima di iniziare, riceverai un briefing completo sulla sicurezza e sulle tecniche di pagaiata. Il percorso si snoda attraverso paesaggi selvaggi e incontaminati, con gole spettacolari e cascate. Durante le pause potrai anche fare il bagno nelle piscine naturali del fiume. L'attività è adatta sia a principianti che a esperti.",
                            DescriptionShort = "Un'avventura adrenalinica tra le rapide di uno dei fiumi più belli dell'Umbria",
                            Duration = "4 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = true,
                            LastEditDate = new DateTime(2023, 7, 10, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 7, 10, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 1,
                            Organiser = "Avventure Italiane",
                            Place = "Scheggino, Umbria",
                            Price = 85m,
                            Sale = 5,
                            Title = "Rafting nelle rapide del fiume Nera",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 12
                        },
                        new
                        {
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            CategoryId = new Guid("a4049ef8-1e86-48bf-b514-3930469ddcbd"),
                            CoverImage = "5f37b647-e33d-440e-88ed-2e0d956f377a.jpg",
                            Description = "Esplora le colline del Montefeltro, al confine tra Marche, Toscana ed Emilia-Romagna, a bordo di una moderna e-bike che ti permetterà di percorrere distanze importanti senza eccessiva fatica. Questo tour guidato ti porterà alla scoperta di antichi borghi medievali, castelli rinascimentali e abbazie secolari, immersi in un paesaggio che ha ispirato i fondali di molti dipinti di Piero della Francesca. Partendo da Urbino, patrimonio UNESCO e culla del Rinascimento italiano, pedalerai lungo strade secondarie poco trafficate e sentieri panoramici, visitando perle nascoste come San Leo, con la sua imponente fortezza, Pennabilli, con i suoi misteriosi giardini, e Sant'Agata Feltria, famosa per il tartufo. Durante il percorso, sono previste soste per visite culturali e per degustare prodotti tipici locali, come il formaggio di fossa, il prosciutto di Carpegna e i vini del territorio. La guida ti racconterà la storia e le leggende di questi luoghi, svelando curiosità e aneddoti poco conosciuti. L'esperienza è adatta a tutti, grazie all'assistenza elettrica delle biciclette che rende accessibili anche i tratti in salita.",
                            DescriptionShort = "Pedalata assistita tra castelli, abbazie e panorami mozzafiato",
                            Duration = "7 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = false,
                            LastEditDate = new DateTime(2023, 8, 10, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 8, 10, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 1,
                            Organiser = "Marche Experience",
                            Place = "Urbino, Marche",
                            Price = 70m,
                            Sale = 0,
                            Title = "Escursione in e-bike nei borghi del Montefeltro",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 12
                        },
                        new
                        {
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            CategoryId = new Guid("b70671a5-3989-4e7c-9cd5-c6343e09fcde"),
                            CoverImage = "44811c06-278a-45e5-8411-717827a59107.jpg",
                            Description = "Concediti un'esperienza di puro relax nelle acque termali di una grotta naturale, formata nei millenni dall'azione dell'acqua sulla roccia calcarea. Questo percorso benessere si svolge in un'antica struttura termale, rinnovata con moderni comfort ma rispettosa dell'ambiente naturale unico. All'interno della grotta, illuminata con luci soffuse, potrai immergerti in diverse piscine di acqua termale a temperature variabili, da 28 a 38 gradi, ricche di minerali benefici per la pelle e l'apparato muscolo-scheletrico. Il percorso prevede anche saune di vapore termale, idromassaggi naturali e cascate per il massaggio cervicale. Un esperto ti guiderà tra le varie tappe del percorso, consigliandoti i tempi ottimali di permanenza in ciascuna area. L'esperienza include un trattamento di fangoterapia e si conclude con una tisana rilassante nella sala relax panoramica, con vista sul parco termale.",
                            DescriptionShort = "Rilassati nelle acque termali naturali di una grotta millenaria",
                            Duration = "3 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = false,
                            LastEditDate = new DateTime(2023, 3, 22, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 3, 22, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 1,
                            Organiser = "Terme Naturali",
                            Place = "Saturnia, Toscana",
                            Price = 95m,
                            Sale = 0,
                            Title = "Percorso benessere in grotta termale",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 12
                        },
                        new
                        {
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            CategoryId = new Guid("1652310e-b8f3-43e7-bd9d-287f73f939b5"),
                            CoverImage = "cf8e8bf0-59b5-44b2-bb5c-478b18b7f767.jpg",
                            Description = "Un'esperienza mozzafiato sul vulcano attivo più grande d'Europa. Questa escursione notturna ti porterà a scoprire l'affascinante paesaggio lunare dell'Etna quando il buio avvolge il vulcano e le stelle brillano intense nel cielo siciliano. Accompagnato da guide vulcanologiche esperte, inizierai il percorso al tramonto per raggiungere i punti panoramici dove godere della vista sulla costa e sui paesi etnei che si illuminano con il calare della notte. Durante il cammino su sentieri di lava solidificata, potrai osservare le colate recenti e i crateri secondari, ascoltando il racconto delle eruzioni storiche e dei miti legati a questo vulcano. Al calare completo della notte, con l'aiuto di lampade frontali, raggiungerai un punto di osservazione privilegiato da cui, con un po' di fortuna, potrai vedere il bagliore rossastro dell'attività vulcanica. L'escursione include una sosta per una cena al sacco in un rifugio di montagna, con degustazione di vini dell'Etna.",
                            DescriptionShort = "Ammira il vulcano attivo sotto il cielo stellato",
                            Duration = "6 ore",
                            IncludedDescription = "L'esperienza include tutto il necessario per goderti l'avventura in totale sicurezza e comfort.",
                            IsDeleted = false,
                            IsFreeCancellable = true,
                            IsInEvidence = false,
                            IsPopular = false,
                            LastEditDate = new DateTime(2023, 4, 10, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            LoadingDate = new DateTime(2023, 4, 10, 11, 0, 56, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 2,
                            Organiser = "Sicilia Avventure",
                            Place = "Catania, Sicilia",
                            Price = 120m,
                            Sale = 0,
                            Title = "Escursione notturna sull'Etna",
                            UserCreatorId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            UserLastModifyId = "3a8073b2-b954-428a-a4b9-6e4b3f5db051",
                            ValidityInMonths = 24
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("1fda0cd4-e54a-47dc-985f-55295e9d0405"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Url = "d709d72d-e919-4e25-90e7-f7174fab8b45.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("5e3b3401-2668-4ec9-a893-ee6c535ddd78"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Url = "82b24643-7e82-4042-be6b-d1704c537371.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("f4840eb1-e492-480f-a418-5f30d68cb215"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Url = "69fee451-9f08-4ab1-bcfb-cf7c8068c3a4.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("eb227c65-5393-4c68-9eab-68406b78a89d"),
                            ExperienceId = new Guid("589aca9c-2b07-42d2-8920-c4406e5da977"),
                            Url = "f12738bf-a7f0-4dc1-a16e-90c3fc6ea823.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("ead880ce-bc68-40ff-982c-639e96f3de15"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Url = "8a18db5b-415d-4c79-ba04-f6c2bd3e534d.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("7f58809a-c241-4e3e-b841-9327111940d4"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Url = "e10af629-01f0-41f5-b078-fe56db331999.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("67673f47-35fd-4c14-a026-d7a61a8936ed"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Url = "d5de5dc4-2e9c-4c2b-8284-85039169bca9.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("92c77996-58e0-44ad-b263-f02f11820a6d"),
                            ExperienceId = new Guid("62947bc9-568c-4c34-a8e1-2fb6f05bca61"),
                            Url = "54b08176-c485-416f-8950-9c74a5b1feea.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("220d183a-888b-4974-b8f6-ee506f647338"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Url = "f2a0c878-277c-4ab7-ac8b-aee7dbf4bfa2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("bba9ae96-13a7-4e28-abcd-63f33f63a28d"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Url = "afab16dd-fb18-4b62-ba16-bea8c4514d68.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("f9ae8eaf-069a-47cd-b19e-6b6e8166165e"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Url = "e46dace3-f0ac-4bca-8fd1-b8e25c815472.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("4bfd8674-47b5-481a-80ca-bc07ab00d627"),
                            ExperienceId = new Guid("bb36c355-2c8e-4a45-9be3-151934e2ff4c"),
                            Url = "199c2fa1-560a-4a26-b0e3-7e59f5b04e9f.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("67d4b845-2959-41cd-ac95-b442a4e32cb5"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Url = "cce26a3b-f6dc-47eb-a624-2bc4df0a7623.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("e20bf13c-a35a-44f6-ba11-12eca65c0366"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Url = "edaf24b2-0a7b-4a18-b44f-eca6ad470460.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("9b2c4cb0-59a6-41b4-84ae-0ddeee3f4e9e"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Url = "800cffd3-c4f6-4395-b444-ff09cf93ba01.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("721063ed-d498-4070-a4e1-940a9f849a14"),
                            ExperienceId = new Guid("8dc3b2f9-850b-42cc-824c-7758112b9370"),
                            Url = "3b6f886f-a15a-45ff-9644-944d0b97eaaa.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("73138467-d5af-499a-8624-f9d5de52a54f"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Url = "77264134-6aab-419e-ad5d-3503697c6823.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00889ac8-a53d-4d5e-b655-aac991787de0"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Url = "206d26ab-33c5-4e4a-b79c-9271e14909ef.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("8fae68b9-e4f8-420a-91a8-4fea7c80b7e0"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Url = "b2bbcf89-6fb0-44a5-924e-6271a8f824b6.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("a06f8821-9e20-4a89-bd19-27db1ac39f11"),
                            ExperienceId = new Guid("cec8f297-d65b-485a-adc3-f015139cd0c2"),
                            Url = "296d02ff-cc6c-4027-81d6-fa75630d9e5b.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("b23f5aef-aa7e-44c9-b38f-29c89fd60831"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Url = "fbb011ba-234d-4b67-9edd-4e5a5f7c103e.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("a9ceabed-f21c-4f01-9303-26852c15524a"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Url = "91ccd7ae-1cec-4462-bae5-a0f97cc43713.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("fd56c8cb-ee90-4140-9134-ab759f6b5be5"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Url = "26ba5e64-1634-41a0-a3de-d08ea7e86d9d.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("93c20292-3ece-4b3a-b5d7-0eeb103f021e"),
                            ExperienceId = new Guid("6f236570-1625-4190-9a4f-0da2d0639386"),
                            Url = "61bf3454-723f-44f2-831e-340673d566fd.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("4e0c61df-cc97-4538-bc2e-b922d1e4e17b"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Url = "e53b1924-4882-4551-bd05-fe72a6a7769e.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("714a64bf-fae0-40c6-a198-ec84d320a03c"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Url = "60b84064-9f5b-454e-a2ea-d38c46c2f03f.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("f2dfc283-587d-4fd9-a29b-599868a05bf6"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Url = "906885f5-840b-4410-bb69-84f6b492c876.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("e83e40ee-9a82-4885-b661-6e1ecb6dadef"),
                            ExperienceId = new Guid("81c17e89-5bc3-42bb-9897-ddf27d111440"),
                            Url = "ae68d8ba-1066-4c99-b1a0-e487da50c0a6.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("8b13d878-8ebc-452e-bf29-b483f72c6887"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Url = "0ff472a2-8be1-43a5-8671-4bf71150b036.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("9ea84996-fb02-49ac-8a73-c315e1bc6abd"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Url = "5d1e782c-7e22-4045-92bc-eb53b15164ce.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("0c665169-d7a3-4781-8ad3-b656ed553183"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Url = "e676f25d-4eb5-4a57-a5ec-93a8b7d0c26c.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("411e1f6a-7bb8-48bb-9a50-8de52bff30fb"),
                            ExperienceId = new Guid("ff3ed239-e178-4632-8385-042286991c66"),
                            Url = "ab6653b8-dcd2-4cf3-9402-78a29db6f26c.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("dac61436-2392-47d6-a679-6f6d1ae94225"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Url = "d8c1f786-4bb3-44df-b5a8-7b806788c246.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("3f4df348-1950-4ce6-9d8a-3b5803cdef49"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Url = "54b7f0e6-9115-4b2c-b0a9-37b2f049eaad.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("79f38fb1-39b2-4f72-a08c-16dac303f0ef"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Url = "0785f2aa-1e76-4d82-ada6-1e70c27621e1.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("0e33f4df-9337-4158-b444-caedb779b555"),
                            ExperienceId = new Guid("0c94ee3c-86f3-4e83-afb2-2a753416227a"),
                            Url = "020a0db7-2ca2-472a-bb79-6fe49dbbb328.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("1d43d597-036f-4c7c-976b-84a49d8a802a"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Url = "87e71440-0f75-4752-9932-89875061ae2a.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("0f3000ac-68fd-46e3-b0cc-bcd40f2927bc"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Url = "cc614324-72a9-4020-bf14-57806546f28f.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("e343c782-8671-4eba-b282-d5fd7a86c9ab"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Url = "0a056b0c-8418-4d1a-8a1e-fd5e366aef78.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("ed5a4c3e-d0b2-4f75-a1e4-825ebe7a748d"),
                            ExperienceId = new Guid("e25b1044-5049-4ca9-954c-db76ae235862"),
                            Url = "39f57bd8-d2db-4d9e-8674-16d015703285.jpg"
                        });
                });

            modelBuilder.Entity("Klicko_be.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 15, 15, 56, 48, 594, DateTimeKind.Utc).AddTicks(3716));

                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR OrderNumber_seq");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Klicko_be.Models.OrderExperience", b =>
                {
                    b.Property<Guid>("OrderExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderExperienceId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderExperiences");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Klicko_be.Models.Auth.ApplicationUserRole", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationRole", "ApplicationRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Klicko_be.Models.CarryWith", b =>
                {
                    b.HasOne("Klicko_be.Models.Experience", "Experience")
                        .WithMany("CarryWiths")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Klicko_be.Models.Cart", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Klicko_be.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Klicko_be.Models.CartExperience", b =>
                {
                    b.HasOne("Klicko_be.Models.Cart", "Cart")
                        .WithMany("CartExperiences")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Klicko_be.Models.Experience", "Experience")
                        .WithMany("CartExperiences")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Klicko_be.Models.Experience", b =>
                {
                    b.HasOne("Klicko_be.Models.Category", "Category")
                        .WithMany("Experiences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", "UserCreator")
                        .WithMany("ExperiencesCreated")
                        .HasForeignKey("UserCreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", "UserLastModify")
                        .WithMany()
                        .HasForeignKey("UserLastModifyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UserCreator");

                    b.Navigation("UserLastModify");
                });

            modelBuilder.Entity("Klicko_be.Models.Image", b =>
                {
                    b.HasOne("Klicko_be.Models.Experience", "Experience")
                        .WithMany("Images")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Klicko_be.Models.Order", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Klicko_be.Models.OrderExperience", b =>
                {
                    b.HasOne("Klicko_be.Models.Experience", "Experience")
                        .WithMany("OrderExperiences")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klicko_be.Models.Order", "Order")
                        .WithMany("OrderExperiences")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Klicko_be.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klicko_be.Models.Auth.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Klicko_be.Models.Auth.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ExperiencesCreated");

                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Klicko_be.Models.Cart", b =>
                {
                    b.Navigation("CartExperiences");
                });

            modelBuilder.Entity("Klicko_be.Models.Category", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("Klicko_be.Models.Experience", b =>
                {
                    b.Navigation("CarryWiths");

                    b.Navigation("CartExperiences");

                    b.Navigation("Images");

                    b.Navigation("OrderExperiences");
                });

            modelBuilder.Entity("Klicko_be.Models.Order", b =>
                {
                    b.Navigation("OrderExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
